spring.application.name=backend

server.port=8081

app.env=dev

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=421342848278-motjp0qraljnr7trg0voqi2plctpchj1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Mongo
spring.data.mongodb.uri=mongodb+srv://ashishsahani6392_db_user:5cTY26AmOGj3xIWJ@cluster0.wsoh2gy.mongodb.net/yatraasync?appName=Cluster0

# JWT
app.jwt.secret=MySuperSecretKeyForJwtAuthentication1234567890ABCDEF
app.jwt.access-expiration=900000
app.frontend.url=http://localhost:3000
